### ISSUE TITLE
Neuanlage eines Ehrenmitglieds ist nicht möglich

### ISSUE THREAD

**Issue by TheFail0r** [wwi16ama/backend#27]
Anlage von Ehrenmitgliedern führt zu nem Abbruch beim Anlegen da keine gültige Transaktion abgefeuert werden kann. Das sollten wir evtl. noch abfangen weil Ehrenmitglied 0 ist und somit keine korrekte Transaction.

**Comment by fwc** [comment]
Es ist ab jetzt möglich, interne Transaktionen mit Betrag **0 €** zu tätigen.
Löst das Problem und sollte keine neuen Erzeugen.
