### ISSUE TITLE
Pilot Log Flugnummer

### ISSUE THREAD

**Issue by buzzdee22** [wwi16ama/backend#34]
Die Flugnummer fängt in jedem Pilot log bei 1 an und zählt von dort an hoch.
die Pilotenlogbücher sind voneinander unabhängig. Stellt euch vor jeder hat sein eigenen Papierbüchlein und zählt darin hoch.
![image](https://user-images.githubusercontent.com/50152135/56985421-97527a80-6b88-11e9-8bab-5ceff998e672.png)

**Comment by fwc** [comment]
Hab mal kurz rübergegoogle't. Es kann sein, dass das für uns sehr kompliziert zu implementieren ist. Es wäre wahrscheinlich deutlich einfacher, das im Frontend umzusetzen und einfach nicht die Datenbank-ID zu zeigen sondern stattdessen die angezeigte NR dynamisch zu berechnen.

**Comment by buzzdee22** [comment]
klärt das am besten selbst mit dem Frontend, denen habe ich aber gestern 6 Issues erstellt und euch nur den einen...
Ich seh das Thema aber relativ kritisch, da es so wie es jetzt ist falsch umgesetzt ist. Wär also gut wenn es geändert wird.

**Comment by fwc** [comment]
Sollte Frontend-seitig gelöst werden
